== Introduction

We're solving the kaggle problem.

== Collaboration standards

Export your new best solutions as a csv file to data/sss/import.
Slice files go into the slices subdirectory.
All files in the root directory, must be the gifts.csv problem or an initialized version of it.

Add the first 4 score digits in the file name.

== Research investigations

For team members only: Add your name to reserve a topic if you're doing it.
Summarize your findings under the topic's title.
Following the scientific method, others are encouraged to try to reproduce your findings and also report their findings below yours.

=== TS vs LA

Geoffrey: On a 1 hour run, TS 7 was worse than LA 400 on slice0.
More importantly: TS flatlined and LA didn't flatline yet.

https://dl.dropboxusercontent.com/u/28857538/2015-12-24_102218_aggregation/index.html[Slice 2 benchmark]

=== Play with Tabu Search ratio's

Done. Results here: https://drive.google.com/file/d/0B2Qb5W2kA2huVnY1eEtYZ2JvVUk/view?usp=sharing
Some conclusions:
* Performance on all slices very similar. Future benchmarks will only be done on one of the slices to save time.
* Very small (~ 1 %) tabu ratios are better than tabu size 7.
* In the long run, LA still most likely better.

=== Play with less/more partitions

TODO

=== Play with TS parameters

TODO

=== Play with LA parameters

TODO

=== Play with nearby selection parameters

Triceo taking this.

=== New nearby meter alternative that ignores latitude

All gifts need to return to the north pole anyway.

TODO

=== Use subchain moves

Near the end, once we're getting stuck, we should definitely start using course-grained moves.

TODO

=== Use custom moves

TODO
