== Introduction

We're solving the kaggle problem.

== How to run our code

* Open the `pom.xml` with IntelliJ or Eclipse

* Run the UI:

** Main class: `org.optaplannerdelirium.sss.app.ReindeerRoutingApp`

** VM options: `-Xmx2G -server`

** Working directory: `santas-stolen-sleigh` (the default)

** Click import button and select a dataset. Highly recommended to select a slice the first time.

* Run the Benchmarker:

** Main class: `org.optaplannerdelirium.sss.app.ReindeerRoutingBenchmarkApp`

** VM options: `-Xmx2G -server` (Add `-Dlogback.level.org.optaplanner=info` to reduce logging verbosity)

** Program arguments (optional): `ge0ffreyLaptop` to run https://github.com/ge0ffrey/santas-stolen-sleigh/blob/master/src/main/resources/org/optaplannerdelirium/sss/benchmark/ge0ffrey/ge0ffreyLaptopBenchmarkConfig.xml[another config than the default]

** Working directory: `santas-stolen-sleigh` (the default)

* Note that starting a Local Search phase on a 100k problem can include up to 1.5 hours with no output due to the nearby selection bootstrap.

== Algorithm description

We didn't have much time to implement this case.
In the first 3 weeks, we worked a few spare hours to build a simple domain.
Only during the Christmas holidays, we had enough time to start optimizing.

=== Partitioning

Once we started, we quickly realized that even simple strategies (such as 2-opt hill climbing)
would take days to flatline, so partitioning was vital. We introduced 3 strategies to partition and solve the problem:

* Whole of 100k
* 5 chunks of 20k each
* 20 slices of 5k each. Most benchmarks use slice 5.

Each of these types go in their own subdirectory of the import dir.

=== Construction Heuristics

TODO

=== Local Search

TODO

== Research investigations log

For team members only: Add your name to reserve a topic if you're doing it.
Summarize your findings under the topic's title.
Following the scientific method, others are encouraged to try to reproduce your findings and also report their findings below yours.

=== TS vs LA

Geoffrey:
On a 1 hour run, TS 7 was worse than LA 400 on slice0.
More importantly: TS flatlined and LA didn't flatline yet.

https://dl.dropboxusercontent.com/u/28857538/2015-12-24_102218_aggregation/index.html[Slice 2 benchmark]

=== Play with Tabu Search ratio's

Lukas:
Results here: https://drive.google.com/file/d/0B2Qb5W2kA2huVnY1eEtYZ2JvVUk/view?usp=sharing
Some conclusions:
* Performance on all slices very similar. Future benchmarks will only be done on one of the slices to save time.
* Very small (~ 1 %) tabu ratios are better than tabu size 7.
* In the long run, LA still most likely better.

=== Investigate combinations of TS and LA

Done. Results here: https://drive.google.com/file/d/0B2Qb5W2kA2huWG1PUHU3enB4djA/view?usp=sharing
To explain: this is two solvers run on the same slice, first TS, then LA. "REVERSE" results are LA first, TS second. All benchmarks have various settings to compare various nearby sizes, tabu ratios etc.

=== Play with less/more partitions

TODO

=== Play with TS parameters

TODO

=== Play with LA parameters

Ondrej:
https://drive.google.com/folderview?id=0B1PRlutaQSliT3N6RlpPS25LcEU&usp=sharing
Played with some parameters, the results seem quite interesting to me.
Please report any observations/conclusions you make so I can investigate further.

=== Play with nearby selection parameters

https://drive.google.com/file/d/0B2Qb5W2kA2huN01GN3AzNjU4VG8/view?usp=sharing
There is a lot to say about this. I'll leave everyone to draw their own conclusions for now.

=== New nearby meter alternative that ignores latitude

All gifts need to return to the north pole anyway.

Geoffrey:
In itself, it's worse than the normal meter

https://dl.dropboxusercontent.com/u/28857538/benchmarks/sss/2015-12-24_163751_aggregation_longitudeMeter/index.html[benchmark result]

=== Use subchain moves

Near the end, once we're getting stuck, we should definitely start using course-grained moves.

TODO

=== Use custom moves

==== 3-opt

TODO

==== K-opt

TODO probalby overkill

==== Ruin & recreate

TODO ge0ffrey
