== Introduction

We're solving the kaggle problem.

== Collaboration standards

Export your new best solutions as a csv file to `data/sss/import`.

We have 3 strategies to solve the problem:

* Whole
* 5 chunks of 20k each
* 20 slices of 5k each. Most benchmarks use slice 5.

Each of these types go in their own subdirectory of the import dir.

Add the first 5 score digits in the file name.
All initialized files must start with the uninitialized filename so the importer can find the problem file too,
for example `gift_slice5.weakestFit_99999score.csv` has the problem file `gift_slice5.csv`.

== Research investigations

For team members only: Add your name to reserve a topic if you're doing it.
Summarize your findings under the topic's title.
Following the scientific method, others are encouraged to try to reproduce your findings and also report their findings below yours.

=== TS vs LA

Geoffrey: On a 1 hour run, TS 7 was worse than LA 400 on slice0.
More importantly: TS flatlined and LA didn't flatline yet.

https://dl.dropboxusercontent.com/u/28857538/2015-12-24_102218_aggregation/index.html[Slice 2 benchmark]

=== Play with Tabu Search ratio's

Done. Results here: https://drive.google.com/file/d/0B2Qb5W2kA2huVnY1eEtYZ2JvVUk/view?usp=sharing
Some conclusions:
* Performance on all slices very similar. Future benchmarks will only be done on one of the slices to save time.
* Very small (~ 1 %) tabu ratios are better than tabu size 7.
* In the long run, LA still most likely better.

=== Play with less/more partitions

TODO

=== Play with TS parameters

TODO

=== Play with LA parameters

TODO

=== Play with nearby selection parameters

https://drive.google.com/file/d/0B2Qb5W2kA2huN01GN3AzNjU4VG8/view?usp=sharing
There is a lot to say about this. I'll leave everyone to draw their own conclusions for now.

=== New nearby meter alternative that ignores latitude

All gifts need to return to the north pole anyway.

In itself, it's worse than the normal meter

https://dl.dropboxusercontent.com/u/28857538/benchmarks/sss/2015-12-24_163751_aggregation_longitudeMeter/index.html

=== Use subchain moves

Near the end, once we're getting stuck, we should definitely start using course-grained moves.

TODO

=== Use custom moves

TODO
